[workspace]
members             = ["package", "test", "contracts/variable-provider"]

[workspace.package]
version             = "0.2.1"
edition             = "2021"
authors             = ["Rhaki"]
license             = "Apache-2.0"

[workspace.dependencies]
cosmwasm-schema     = "1.3.0"
cosmwasm-std        = "1.5.0"
cw-storage-plus     = "1.1.0"
cw-multi-test       = "0.16.5"
schemars            = "0.8.10"
serde               = { version = "1.0.145", default-features = false, features = ["derive"] }
rhaki-cw-plus       = "0.6.8"
thiserror           = "1.0.31"
variable-provider-pkg = { path = "./package", version="0.2.1" }